db:
  host: localhost
  port: 5432
  db: misskey
  user: example-misskey-user
  pass: example-misskey-pass

meilisearch:
  host: localhost
  port: 7700
  apiKey: 'your-api-key'
  index: 'your-index'
  scope: local